### ISSUE TITLE
eros dev 命令出错

### ISSUE THREAD

**Issue by mylonly** [bmfe/eros-cli#1]
执行eros dev 之后提示需要sudo
改为执行sudo eros dev 之后提示出错，截图如下：
![wx20171205-163337](https://user-images.githubusercontent.com/7758978/33597358-2bdc23a0-d9da-11e7-8414-3ddc6ca19ba7.png)

**Comment by mylonly** [comment]
已经找到原因了，是我引入的js文件的问题

**Comment by PerseveranceZ** [comment]
https://github.com/bmfe/eros-template/wiki/%E7%8E%AF%E5%A2%83%E7%9B%B8%E5%85%B3
需要cd到项目中来执行命令

**Comment by ddqre12345** [comment]
@mylonly 能说一下怎么解决的么？我也遇到同样的问题，谢谢

**Comment by PerseveranceZ** [comment]
@ddqre12345 按照上面的回复 解决了吗？
