### ISSUE TITLE
shasumNotMatchError

### ISSUE THREAD

**Issue by sssnail** [bmfe/eros-cli#11]
executed "cnpm i eros-cli -g" occured an error:

![image](https://user-images.githubusercontent.com/16909657/36070763-c8ce6226-0f3c-11e8-95a5-9a5aa92c8ad8.png)

node version is 8.0.0. updated it to the latest version. succeeded.

**Comment by PerseveranceZ** [comment]
node version is 8.0.0. 

updated it to the latest version. succeeded.

![image](https://user-images.githubusercontent.com/13193407/36070786-4e7749a6-0f3d-11e8-834d-6669dcc2e0ea.png)
