### ISSUE TITLE
升级weex-loader 吧 现在的版本不支持 recycle-list

### ISSUE THREAD

**Issue by hetian9288** [bmfe/eros-cli#16]
升级weex-loader 吧 现在的版本不支持 recycle-list

**Comment by PerseveranceZ** [comment]
@hetian9288 能提供下 weex-loader 的版本吗

**Comment by hetian9288** [comment]
weex-loader@0.7.2
http://weex.apache.org/cn/references/components/recycle-list.html#ji-ben-yong-fa

**Comment by PerseveranceZ** [comment]
@hetian9288 0.7.2 昨天尝试升级了下 会报出大量 warning ，并且不支持了 sass @import 引入，也不识别变量，这边还是升级到了 `"weex-loader": "^0.5.3"`, 官方目前也是这个版本，待官方解决后才能升级。

**Comment by PerseveranceZ** [comment]
@hetian9288 https://github.com/weexteam/weex-loader/issues/65 待这个问题官方给出回复的我在升级吧，不然对于已有使用 eros 的项目 直接影响到了业务。

**Comment by PerseveranceZ** [comment]
@hetian9288 在 `2.0.7-beta.1` 升级到了 0.7.2
