### ISSUE TITLE
 remove android umeng appId 导致报错

### ISSUE THREAD

**Issue by antbuff** [bmfe/eros-cli#27]
![jietu20180505-110335](https://user-images.githubusercontent.com/26304210/39659171-3ae20a12-5055-11e8-9292-f9c932e1511d.jpg)

似乎模板中的android项目依然依赖这个

**Comment by PerseveranceZ** [comment]
@antbuff 新版本中 umeng 已经拆分出来至独立插件，如果还是老项目还继续使用 2.0.7@beta 版本，如果已经更新到脚手架最新，重新 init 进行迁移
