### ISSUE TITLE
参数冲突。

### ISSUE THREAD

**Issue by Z-Janp** [bmfe/eros-cli#28]
version: 2.0.8-beta.1
isSSL与requestUrl 赋值冲突

`isSSL = argv.s || argv.ssl`

`requestUrl = argv.s || argv.send`

执行 

`eros pack -s http://localhost:3001/app/add`

result: 
`jsServer":"https://192.168.17.52:undefined"`

**Comment by PerseveranceZ** [comment]
@Z-Janp 感谢反馈 下次可以给我们直接 pr 啊

**Comment by PerseveranceZ** [comment]
@Z-Janp fixed in `eros-cli@2.0.8-beta.2`.
